/*
 * CFD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	CartApiService := openapi.NewCartApiService()
	CartApiController := openapi.NewCartApiController(CartApiService)

	ImageApiService := openapi.NewImageApiService()
	ImageApiController := openapi.NewImageApiController(ImageApiService)

	MenuApiService := openapi.NewMenuApiService()
	MenuApiController := openapi.NewMenuApiController(MenuApiService)

	router := openapi.NewRouter(CartApiController, ImageApiController, MenuApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
